[tools]
"aqua:dandavison/delta" = "0.18.2"
"aqua:jqlang/jq" = "1.7.1"
node = "24.12.0"
"npm:@anthropic-ai/claude-code" = "2.1.5"
"pipx:gitingest" = "0.3.1"
pkl = "0.30.2"
python = "3.14.2"
"github:sst/opencode" = "1.1.14"
