[tools]
"aqua:dandavison/delta" = "0.18.2"
"aqua:jqlang/jq" = "1.7.1"
"github:sst/opencode" = "1.1.14"
"npm:@anthropic-ai/claude-code" = "2.1.19"
"npm:@openai/codex" = "0.91.0"
"pipx:gitingest" = "0.3.1"
node = "24.13.0"
pkl = "0.30.2"
python = "3.14.2"
