[tools]
"aqua:dandavison/delta" = "0.18.2"
"aqua:jqlang/jq" = "1.7.1"
node = "24.11.1"
"npm:@anthropic-ai/claude-code" = "2.0.50"
"pipx:gitingest" = "0.3.1"
pkl = "0.30.0"
python = "3.14.0"
"ubi:sst/opencode" = "1.0.115"
