name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Run ShellCheck
        run: |
          shellcheck install.sh
          shellcheck bin/setup
          shellcheck bin/test

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest] # macos-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Setup mise
        uses: jdx/mise-action@6d1e696aa24c1aa1bcc1adea0212707c71ab78a8 # v3.6.1
      - name: Install chezmoi
        run: |
          GIT_USER_NAME="CI Test User" GIT_USER_EMAIL="ci@example.com" ./install.sh
      - name: Install test dependencies
        run: |
          ./bin/setup
      - name: Run test suite
        run: |
          ./bin/test